---
execute:
    echo: false
    warning: false
---

# ADVERSE_REACTION_RESERVE {.unnumbered}

```{r,eval=TRUE,echo=FALSE}
#| label: source-filefolder
dr <- "C:/Users/ajp5303/OneDrive - Washington State Executive Branch Agencies/source_scripts"
```

```{r,eval=TRUE,echo=FALSE}
#| label: source-files
source(paste0(dr,"/dbconnection.R"))
source(paste0(dr,"/dqguide_functions.R"))
```

## Description

The address_reaction_reserve table contains a list of records with an associated adverse reaction code.

## Columns

```{r}
#| label: advrr-colnames
tibble(Columns = (tbl(synapse, in_schema("dbo", "H33_ADVERSE_REACTION_RESERVE")) %>% colnames()),
       Type = tbl(synapse, in_schema("dbo", "H33_ADVERSE_REACTION_RESERVE")) %>% head(1) %>% as_tibble() %>%
                  sapply(class)
  ) %>%
  gt() %>%
  gt_theme_espn()
```

## Category Description

This section contains variable coding for relevant columns within the adverse reaction table.

```{r}
#| label: tab-advrrtab

```

## Statistics

```{r}
#| label: advrr-stats
tibble(columncnt = (tbl(synapse, in_schema("dbo", "H33_ADVERSE_REACTION_RESERVE")) %>% ncol()),
       rowcnt = (tbl(synapse, in_schema("dbo", "H33_ADVERSE_REACTION_RESERVE"))) %>% nrow2()
  ) %>%
  gt() %>%
  cols_label(columncnt = "Number of Columns",
             rowcnt = "Number of Rows")  %>%
  gt_theme_espn()
```
