---
execute:
    echo: false
    warning: false
---

# PATIENT_VACCINE_DEFERRAL {.unnumbered}

```{r,eval=TRUE,echo=FALSE}
#| label: source-filefolder
dr <- "C:/Users/ajp5303/OneDrive - Washington State Executive Branch Agencies/source_scripts"
```

```{r,eval=TRUE,echo=FALSE}
#| label: source-files
source(paste0(dr,"/dbconnection.R"))
source(paste0(dr,"/dqguide_functions.R"))
```

## Description

Description

## Columns

```{r}
#| label: ptvacdef-colnames
tibble(Columns = (tbl(synapse, in_schema("dbo", "H33_PATIENT_VACCINE_DEFERRAL")) %>% colnames()),
       Type = tbl(synapse, in_schema("dbo", "H33_PATIENT_VACCINE_DEFERRAL")) %>% head(1) %>% as_tibble() %>% sapply(class)
       ) %>%
 gt() %>%
 gt_theme_espn()
```

## Category Description

Description

## Statistics

```{r}
#| label: ptvacdef-stats
tibble(columncnt = (tbl(synapse, in_schema("dbo", "H33_PATIENT_VACCINE_DEFERRAL")) %>% ncol()),
       rowcnt = (tbl(synapse, in_schema("dbo", "H33_PATIENT_VACCINE_DEFERRAL"))) %>% nrow2()
       ) %>%
  gt() %>%
  cols_label(columncnt = "Number of Columns",
             rowcnt = "Number of Rows")  %>%
  gt_theme_espn()
```
