---
execute:
    echo: false
    warning: false
---

# SEROLOGY_RESERVE {.unnumbered}

```{r,eval=TRUE,echo=FALSE}
#| label: source-filefolder
dr <- "C:/Users/ajp5303/OneDrive - Washington State Executive Branch Agencies/source_scripts"
```

```{r,eval=TRUE,echo=FALSE}
#| label: source-files
source(paste0(dr,"/dbconnection.R"))
source(paste0(dr,"/dqguide_functions.R"))
```

## Description

The serology_reserve table contains information on patient records with a serology result. Details on the serology draw date, type, and titer value are included.

## Columns

```{r}
#| label: serres-colnames
tibble(Columns = (tbl(synapse, in_schema("dbo", "H33_SEROLOGY_RESERVE")) %>% colnames())) %>%
 mutate(Type = typeof(Columns)) %>%
 gt() %>%
 gt_theme_espn()
```

## Category Description

```{r}
#| label: serres-table
serres_tabl <-
tibble(Coding = c(#serology_type_codes top 16
                  "1","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64"),

               
Description = c(#serology_type_codes
"Varicella",
"Serology confirmed Mumps",
"Serology confirmed Rubella",
"Serology confirmed Measles",
"Serology confirmed Varicella",
"Serology confirmed Hepatitis B",
"Serology confirmed Hepatitis A",
"SARS-CoV-2 IgG qualitative",
"SARS-CoV-2 RdRp gene result",
"SARS-CoV-2 result",
"Overall SARS-CoV-2 result",
"SARS-CoV-2 N gene result",
"SARS-related CoV result",
"SARS-CoV-2 ORF1ab region result",
"SARS-CoV-2 Ab qualitative",
"TB Gold, QuantiFERON"),
                      
       Variable = c(#group_code category
                    "SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE","SEROLOGY_TYPE_CODE"),
                           
      Space = " ") %>%
  
       gt(rowname_col = "Space", groupname_col = "Variable") %>%
       tab_header(title = "Variable Coding"
       ) %>%
       cols_width(Coding~px(200),
                  Description~px(400),
                  Space~px(100)) %>%
       cols_align(align = "left") %>%
       gt_theme_espn()

serres_tabl
```

## Statistics

```{r}
#| label: serres-stats
tibble(columncnt = (tbl(synapse, in_schema("dbo", "H33_SEROLOGY_RESERVE")) %>% ncol()),
       rowcnt = (tbl(synapse, in_schema("dbo", "H33_SEROLOGY_RESERVE"))) %>% nrow2()
       ) %>%
  gt() %>%
  cols_label(columncnt = "Number of Columns",
             rowcnt = "Number of Rows")  %>%
  gt_theme_espn()
```

:::
